- hosts: terraformansible
  gather_facts: no
  tasks:
   
    - name: Instalando o pthon3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes
   
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
          - pandas
          - numpy
   
    - name: Iniciando projeto
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
   
    - name: Alterando os hosts do settings.py
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

# esse foi o exemplo usado no começo para subir a maquina com um arquivo ja criado nela
#- hosts: terraform-ansible

    - name: criando o arquivo
      copy:
       dest: /home/ubuntu/index.html
       content: <h1>. venv/bin/activate</h1>
                <h1>django-admin startproject setup .</h1>
                <h1>python manage.py runserver 0.0.0.0:8000</h1>
                <h1>ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts.yml</h1>
    - name: criando o servidor 
      shell: "nohup busybox httpd - f -p 8080 &"


